// <auto-generated />
namespace CPMS.API.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initaial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initaial));
        
        string IMigrationMetadata.Id
        {
            get { return "202404071740469_initaial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
